# Generated by Django 4.1.2 on 2023-01-21 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tag_produit_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='tag',
        ),
        migrations.AddField(
            model_name='produit',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.tag'),
        ),
    ]
