# Generated by Django 4.1.2 on 2023-01-25 01:43

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_tag_marque_rename_tag_produit_marque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.filepath),
        ),
    ]
